version: '2'
services:
  fhem-tablet-ui:
    container_name: tablet-ui
    image: raigen/rpi-fhem-tablet-ui
    volumes:
      - ./index.html:/usr/share/nginx/html/tablet/index.html
    ports:
      - "8080:80"
